import React from "react";
import Head from "next/head";
import { Box } from "@mui/system";
import { gql } from "@apollo/client";
import styles from "../styles/Home.module.css";
import { Button, TextField, Typography } from "@mui/material";
import VpnKeyIcon from "@mui/icons-material/VpnKey";
import MailOutlineIcon from "@mui/icons-material/MailOutline";
import QuoteCarousel from "../components/QuoteCarousel";
import Link from "next/link";

const FetchPosts = gql`
  query GetPosts {
    getPosts {
      id
      post
      user {
        username
        id
      }
    }
  }
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="box">
        <div className="wave"></div>
      </div>

      <Typography variant="h3" style={{ fontWeight: 900 }}>
        Remedy
      </Typography>
      <Box fontSize=".86rem" mb={5}>
        The Public Diary
      </Box>

      <Box sx={{ maxWidth: "300px" }}>
        <Box sx={{ display: "flex", alignItems: "flex-end" }}>
          <MailOutlineIcon sx={{ color: "action.active", mr: 1, my: 0.5 }} />
          <TextField
            label="Email"
            id="input-with-icon-adornment"
            variant="standard"
            style={{ fontSize: ".8rem" }}
          />
        </Box>
        <Box my={2}></Box>
        <Box sx={{ display: "flex", alignItems: "flex-end" }}>
          <VpnKeyIcon sx={{ color: "action.active", mr: 1, my: 0.5 }} />
          <TextField
            label="Password"
            type="password"
            variant="standard"
            id="input-with-icon-adornment"
          />
        </Box>
        <Box my={2}></Box>
        <Link href="/feeds">
          <Button
            style={{
              color: "#FFF",
              width: "100%",
              background: "rgba(255,255,255,0.05)",
              fontWeight: 600,
              fontSize: ".83rem",
              letterSpacing: "1px",
            }}
            size="large"
            disableElevation
            // onClick={() => {
            //   if (Notification.permission === "granted") {
            //     const notification = new Notification("New message from Remedy", {
            //       body: "Hi Jean, Adu has mentioned you in the comments!",
            //     });
            //   } else if (Notification.permission !== "denied") {
            //     Notification.requestPermission((permission) => {
            //       const notification = new Notification(
            //         "New message from Remedy",
            //         {
            //           body: "Hi Jean, Lenas has mentioned you in the comments!",
            //         }
            //       );
            //     });
            //   }
            // }}
          >
            Login
          </Button>
        </Link>
        <Link href="/feeds">
          <Box
            mt={2}
            sx={{
              color: "#67D",
              fontSize: ".8rem",
              cursor: "pointer",
            }}
          >
            Don't have account?
          </Box>
        </Link>
      </Box>

      <QuoteCarousel />
    </div>
  );
}

export async function getStaticProps() {
  // const { data } = await client.query({
  //   query: FetchPosts,
  // });

  return {
    props: {
      //     countries: data,
    },
  };
}
